(() => {
const STORAGE_KEY="psychologyAcademyWeek1";
const state={solved:[],notes:{},activeChallenge:null};
const challengeData={
notebook:{title:"Wundt's Laboratory Notebook",prompt:"Which statement best describes psychology?",options:["The study of dreams and hidden meanings only","The scientific study of behavior and mental processes","The study of personality types only"],correctIndex:1,feedback:"Correct. Psychology examines observable behavior and internal mental processes using scientific methods.",hint:"Look for the answer that includes both behavior and internal processes.",code:"M",inventory:"Wundt Laboratory Note"},
portrait:{title:"The Portrait Marked 1879",prompt:"Who is most closely associated with establishing an early psychology laboratory in Leipzig in 1879?",options:["Wilhelm Wundt","Sigmund Freud","B. F. Skinner"],correctIndex:0,feedback:"Correct. Wilhelm Wundt established a laboratory dedicated to psychological research in Leipzig in 1879.",hint:"His last name begins with W.",code:"I",inventory:"1879 Museum Plaque"},
mirror:{title:"The Structuralist Mirror",prompt:"Structuralism was most interested in:",options:["How consequences shape voluntary behavior","The basic elements of conscious experience","How culture influences group behavior"],correctIndex:1,feedback:"Correct. Structuralism attempted to identify the basic elements of conscious experience.",hint:"Think about breaking conscious experience into parts.",code:"N",inventory:"Structuralist Mirror Fragment"},
compass:{title:"The Functionalist Compass",prompt:"Functionalism focused on:",options:["How thoughts and behaviors help people adapt","The interpretation of dreams","The electrical activity of neurons only"],correctIndex:0,feedback:"Correct. Functionalism examined how mental processes and behavior help organisms adapt to their environments.",hint:"Ask what purpose a thought or behavior serves.",code:"D",inventory:"Functionalist Compass"},
lever:{title:"Skinner's Lever",prompt:"Which perspective emphasizes observable behavior and learning through consequences?",options:["Behavioral perspective","Humanistic perspective","Psychodynamic perspective"],correctIndex:0,feedback:"Correct. Behaviorism emphasizes observable behavior and the role of learning and consequences.",hint:"Think about Skinner, reinforcement, and observable behavior.",code:"S",inventory:"Behavioral Research Key"},
magnifier:{title:"The Scientific Magnifying Glass",prompt:"What best separates psychological science from personal opinion?",options:["Psychological explanations never change","Psychologists systematically test ideas and evaluate evidence","Psychologists rely mainly on intuition"],correctIndex:1,feedback:"Correct. Psychological science depends on systematic observation, measurement, research, and evidence.",hint:"Look for the answer that describes testing and evidence.",code:"1",inventory:"Scientific Evidence Lens"}};
const els={};
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(s&&typeof s==="object"){state.solved=Array.isArray(s.solved)?s.solved:[];state.notes=s.notes&&typeof s.notes==="object"?s.notes:{}}}catch(e){console.warn("Saved progress could not be loaded.",e)}}
function cache(){els.challengeRegion=document.getElementById("challenge-region");els.progress=document.getElementById("mission-progress");els.progressText=document.getElementById("progress-text");els.inventory=document.getElementById("inventory-list");els.codeList=document.getElementById("code-list");els.finalLock=document.getElementById("final-lock");els.lockFeedback=document.getElementById("lock-feedback");els.resetButton=document.getElementById("reset-progress");els.notes=[...document.querySelectorAll("[data-note-key]")];els.objectButtons=[...document.querySelectorAll("[data-challenge-id]")]}
function renderProgress(){const n=state.solved.length;els.progress.value=n;els.progress.max=6;els.progressText.textContent=`${n} of 6 exhibits solved`;els.inventory.innerHTML="";els.codeList.innerHTML="";if(n===0){els.inventory.innerHTML="<li>No evidence collected yet.</li>";els.codeList.innerHTML="<li>No code characters collected yet.</li>"}else{state.solved.forEach(id=>{const item=challengeData[id];const li=document.createElement("li");li.textContent=item.inventory;els.inventory.appendChild(li);const ci=document.createElement("li");ci.textContent=`${item.title}: ${item.code}`;els.codeList.appendChild(ci)})}els.objectButtons.forEach(button=>{const id=button.dataset.challengeId;const solved=state.solved.includes(id);button.setAttribute("aria-pressed",solved?"true":"false");const status=button.querySelector(".status-text");if(status)status.textContent=solved?"Solved":"Not yet solved"});els.finalLock.classList.toggle("hidden",n!==6)}
function renderChallenge(id){state.activeChallenge=id;const c=challengeData[id],solved=state.solved.includes(id);els.challengeRegion.innerHTML=`<section class="challenge" aria-labelledby="challenge-title"><h2 id="challenge-title">${c.title}</h2><p>${c.prompt}</p><div class="option-list" aria-label="Answer choices">${c.options.map((o,i)=>`<button class="option-button" type="button" data-answer-index="${i}">${o}</button>`).join("")}</div><button class="secondary" type="button" id="show-hint">Show hint</button><div id="challenge-feedback" class="feedback" role="status" aria-live="polite">${solved?`This exhibit is already solved. Your code character is <strong>${c.code}</strong>.`:"Choose the best answer."}</div></section>`;els.challengeRegion.scrollIntoView({behavior:"smooth",block:"start"});[...els.challengeRegion.querySelectorAll("[data-answer-index]")].forEach(b=>b.addEventListener("click",()=>checkAnswer(id,Number(b.dataset.answerIndex))));document.getElementById("show-hint").addEventListener("click",()=>{const f=document.getElementById("challenge-feedback");f.className="feedback";f.textContent=`Hint: ${c.hint}`})}
function checkAnswer(id,index){const c=challengeData[id],f=document.getElementById("challenge-feedback");if(index===c.correctIndex){if(!state.solved.includes(id)){state.solved.push(id);saveState()}f.className="feedback correct";f.innerHTML=`${c.feedback}<br><strong>Code character: ${c.code}</strong>`;renderProgress()}else{f.className="feedback incorrect";f.textContent="That answer is not correct yet. Review the course materials or use the hint, then try again."}}
function setupNotes(){els.notes.forEach(t=>{const k=t.dataset.noteKey;t.value=state.notes[k]||"";t.addEventListener("input",()=>{state.notes[k]=t.value;saveState()})})}
function setupLock(){[...document.querySelectorAll("[data-lock-code]")].forEach(b=>b.addEventListener("click",()=>{if(b.dataset.lockCode==="MINDS1"){els.lockFeedback.className="feedback correct";els.lockFeedback.innerHTML="<h3>The Final Gallery Opens</h3><p>You recovered the missing psychology notes.</p><p><strong>Completion phrase:</strong> Evidence unlocks the mind.</p>"}else{els.lockFeedback.className="feedback incorrect";els.lockFeedback.textContent="The lock remains closed. Check the order of your six code characters and try again."}}))}
function setupReset(){els.resetButton.addEventListener("click",()=>{if(!window.confirm("Reset all Week 1 mission progress and notebook entries?"))return;localStorage.removeItem(STORAGE_KEY);state.solved=[];state.notes={};els.challengeRegion.innerHTML="";els.lockFeedback.textContent="";els.notes.forEach(t=>t.value="");renderProgress()})}
function init(){loadState();cache();setupNotes();setupLock();setupReset();els.objectButtons.forEach(b=>b.addEventListener("click",()=>renderChallenge(b.dataset.challengeId)));renderProgress()}
document.addEventListener("DOMContentLoaded",init);
})();